language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
  - ./gradlew checkstyle build